apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-arms
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-arms
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-arms
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-arms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-arms
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fmfs-tenant/rhtap-demo-app/hacbs-test-project-arms@sha256:21aea93159a8a3b93279a15628886539ec0d18c7c30c0f98fcd45f7214a5fcd6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
