apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-arms
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fmfs-tenant/rhtap-demo-app/hacbs-test-project-arms@sha256:dca9e712f4fe99326458fdbb651fc670b7bb6128314effb89ec58e073fdd30dc
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
